apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        component: latency-controller
        tier: control-plane
    name: latency-controller
    namespace: polaris
spec:
    selector:
        matchLabels:
            component: latency-controller
            tier: control-plane
    replicas: 1
    template:
        metadata:
            labels:
                component: latency-controller
                tier: control-plane
        spec:
            serviceAccountName: latency-controller
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  # Ensure that the controller is only scheduled on Intel 64-bit nodes.
                                  - key: kubernetes.io/arch
                                    operator: In
                                    values:
                                        - amd64
            tolerations:
                # Ensure that the controller can be scheduled on master nodes.
                - key: node-role.kubernetes.io/master
                  operator: Exists
                  effect: NoSchedule
            containers:
                - image: nicolobartelucci/latency-controller:latest
                  name: slo-controller
                  resources:
                      limits:
                          cpu: 1000m
                          memory: 512Mi
                  env:
                      # The hostname and port of the Prometheus service:
                      - name: PROMETHEUS_HOST
                        value: prometheus-release-1-prome-prometheus.default.svc
                      - name: PROMETHEUS_PORT
                        value: '9090'
                      # Workaround for an issue with kubernetes-client when using IPv6 (https://github.com/kubernetes-client/javascript/issues/599)
                      - name: KUBERNETES_SERVICE_HOST
                        value: kubernetes.default.svc
                  securityContext:
                      privileged: false

